global using FastEndpoints;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Storage;
global using Microsoft.Extensions.DependencyInjection;
global using System.Collections;
global using System.Linq.Expressions;
global using CSharpFunctionalExtensions;
global using Microsoft.AspNetCore.Http;
global using FluentValidation.Results;
